Example 30: Flink ML
Does not work (needed old flink version 1.8.2)

Caused by: java.lang.NoSuchMethodError: scala.Predef$.longArrayOps([J)Lscala/collection/mutable/ArrayOps;
	at org.apache.flink.ml.recommendation.ALS$$anonfun$createOutBlockInformation$1.apply(ALS.scala:791)
	at org.apache.flink.ml.recommendation.ALS$$anonfun$createOutBlockInformation$1.apply(ALS.scala:787)
	at org.apache.flink.api.scala.CoGroupDataSet$$anon$1.coGroup(CoGroupDataSet.scala:89)

This error was recurring last week.